### ISSUE TITLE
AiNiee 4.73 按这个教程搭建好后 无法正常链接到Sakura启动的服务器

### ISSUE THREAD

**Issue by legend0702** [neavo/OneClickLLAMA#1]
给我一种完全没有调用到那个端口的感觉 这是啥意思？
![image](https://github.com/user-attachments/assets/3cba0aa2-e579-414e-889e-6e79fd53689f)
我后面用Sakura那边测试用的web端api 是能正常调用到的
![image](https://github.com/user-attachments/assets/a8f6abb8-a2c0-493d-a242-335863575fb1)
是API更新的问题？v0.9 跟 v0.10pre 我都试了阿 都一样错误  给我一种完全没有调用到的感觉 隔壁控制台一点反应都没有

**Comment by legend0702** [comment]
仔细看了下不同 原来是请求地址默认不带http导致协议直接失败了
在127.0.0.1最前面加了http://就好使了 建议默认带上阿

**Comment by legend0702** [comment]
关闭问题

**Comment by neavo** [comment]
> 仔细看了下不同 原来是请求地址默认不带http导致协议直接失败了 在127.0.0.1最前面加了[http://就好使了](http://%E5%B0%B1%E5%A5%BD%E4%BD%BF%E4%BA%86) 建议默认带上阿

是这样吗，我还真没太注意过，建议去 AiNiee 那边报一下 issue
