### ISSUE TITLE
使用 AiNiee 翻译器作業時成功過一次之後就沒有成功過

### ISSUE THREAD

**Issue by Ausen1123** [neavo/OneClickLLAMA#2]
我是依照說明的方式執行的(原本也有成功過)，之後要再使用的時候就會失敗．如下圖
![image](https://github.com/user-attachments/assets/0ed9cc5b-46b0-404c-b9f3-ee1d789dbe3e)
但是我D槽沒有這個檔案
D:\a\llama.cpp\llama.cpp\ggml\src\ggml-cuda\rope.cu<==我不是放在這裡
F:\rpgmaker\Translate\dist\SakuraLLMServer_20240811<==這才是我放的位置

**Comment by neavo** [comment]
> 我是依照說明的方式執行的(原本也有成功過)，之後要再使用的時候就會失敗．如下圖 ![image](https://private-user-images.githubusercontent.com/180830532/365428036-0ed9cc5b-46b0-404c-b9f3-ee1d789dbe3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODg5MjEsIm5iZiI6MTcyNTc4ODYyMSwicGF0aCI6Ii8xODA4MzA1MzIvMzY1NDI4MDM2LTBlZDljYzViLTQ2YjAtNDA0Yy1iOWYzLWVlMWQ3ODlkYmUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwOTQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjViOWQ5MDcyZjc3YWUzZWViMTNkNTUxOTlmYWVhMThiZWY5N2EwNTQwMjUxNzg0Y2I1YmJjMjY4NzY2NzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GZdjFnW_IoXmCqOrljnmqT5w9sioSJqq0VBoMpwPJJk) 但是我D槽沒有這個檔案 D:\a\llama.cpp\llama.cpp\ggml\src\ggml-cuda\rope.cu<==我不是放在這裡 F:\rpgmaker\Translate\dist\SakuraLLMServer_20240811<==這才是我放的位置

如果时跑了一会儿才报错的话，一般是因为文本超长了，可以把 Token 限制再调小一点试试，比如 300

**Comment by Ausen1123** [comment]
調整成300之後重新跑過了一遍，到目前為止沒有問題，謝謝解答
