### ISSUE TITLE
程序在slot context shift后报错退出

### ISSUE THREAD

**Issue by fnESHJA** [neavo/OneClickLLAMA#3]
![image](https://github.com/user-attachments/assets/8cd1c049-7aaf-4aba-97ff-5faafdc884f8)
如图，程序在报告slot context shift后报错退出，此时没有爆显存。在此之前程序会稳定运行5至30分钟不报错。

GPU为4070lp，8gb显存，cuda版本为12.2，显卡驱动版本为最新的560.94，使用的模型为sakura0.92_1.11_IQ3XSS。内存为32g，cpu为7845hx，均不构成瓶颈。

**Comment by neavo** [comment]
> ![image](https://private-user-images.githubusercontent.com/83067896/365434585-8cd1c049-7aaf-4aba-97ff-5faafdc884f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTcyNzUsIm5iZiI6MTcyNTc5Njk3NSwicGF0aCI6Ii84MzA2Nzg5Ni8zNjU0MzQ1ODUtOGNkMWMwNDktN2FhZi00YWJhLTk3ZmYtNWZhYWZkYzg4NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDEyMDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZjcyNjBlMWU2YjU2NjFkMjgxZDZhOTUxNDRmYWE3MjYwOTI4NWZlM2UyNGE0YjA3NWEwOTljZTNkZjBmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OrgBNEfvvXLBjNXyOXy0etY7R6l05fWaVxktKG3X9o) 如图，程序在报告slot context shift后报错退出，此时没有爆显存。在此之前程序会稳定运行5至30分钟不报错。
> 
> GPU为4070lp，8gb显存，cuda版本为12.2，显卡驱动版本为最新的560.94，使用的模型为sakura0.92_1.11_IQ3XSS。内存为32g，cpu为7845hx，均不构成瓶颈。

参考 https://github.com/neavo/SakuraLLMServer/issues/2

这是 llama.cpp 的 BUG

启用 KV 量化上下文只要超限哪怕一点点就直接崩

**Comment by fnESHJA** [comment]
确定是tokens的问题。在更改每次发送的tokens为200之后，连续运行4h，发送2000000tokens之后仍然正常运行。建议更改readme.md，加上报错需要减少tokens的描述。

**Comment by neavo** [comment]
> 确定是tokens的问题。在更改每次发送的tokens为200之后，连续运行4h，发送2000000tokens之后仍然正常运行。建议更改readme.md，加上报错需要减少tokens的描述。

好主意
