### ISSUE TITLE
关于Galtransl模型在AiNiee上的参数调整

### ISSUE THREAD

**Issue by frostylight** [neavo/OneClickLLAMA#5]
AiNiee上SakuraLLM的参数默认是温度0.1、Top P 0.3、重复惩罚0，源自[github/SakuraLLM](https://github.com/SakuraLLM/SakuraLLM?tab=readme-ov-file#%E6%8E%A8%E7%90%86)
GalTransl-7B模型在[huggingface](https://huggingface.co/SakuraLLM/GalTransl-7B-v2.6#%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F)上的推荐参数是温度0.2；Top P 0.8；重复惩罚+0.1

是不是使用huggingface上推荐参数效果会更好一点

**Comment by neavo** [comment]
> AiNiee上SakuraLLM的参数默认是温度0.1、Top P 0.3、重复惩罚0，源自[github/SakuraLLM](https://github.com/SakuraLLM/SakuraLLM?tab=readme-ov-file#%E6%8E%A8%E7%90%86) GalTransl-7B模型在[huggingface](https://huggingface.co/SakuraLLM/GalTransl-7B-v2.6#%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F)上的推荐参数是温度0.2；Top P 0.8；重复惩罚+0.1
> 
> 是不是使用huggingface上推荐参数效果会更好一点

根据我与 Sakura 和 GalTransl 的作者们的沟通来看
目前对于翻译参数到底什么最佳其实没什么定论，都是拍脑袋出来的经验数值，有兴趣可以自己调一下对比看看
我也对结论十分好奇

P.S
你对 `重复惩罚 +0.1` 的理解有误
这句话指的并非是 `frequency_penalty` 固定为 0.1
而是指在检测到退化时下一次请求 +0.1，目前各个翻译器都会自动处理，所以不用关注这个参数

**Comment by frostylight** [comment]
> > AiNiee上SakuraLLM的参数默认是温度0.1、Top P 0.3、重复惩罚0，源自[github/SakuraLLM](https://github.com/SakuraLLM/SakuraLLM?tab=readme-ov-file#%E6%8E%A8%E7%90%86) GalTransl-7B模型在[huggingface](https://huggingface.co/SakuraLLM/GalTransl-7B-v2.6#%E8%AF%B7%E6%B1%82%E6%96%B9%E5%BC%8F)上的推荐参数是温度0.2；Top P 0.8；重复惩罚+0.1
> > 是不是使用huggingface上推荐参数效果会更好一点
> 
> 根据我与 Sakura 和 GalTransl 的作者们的沟通来看 目前对于翻译参数到底什么最佳其实没什么定论，都是拍脑袋出来的经验数值，有兴趣可以自己调一下对比看看 我也对结论十分好奇
> 
> P.S 你对 `重复惩罚 +0.1` 的理解有误 这句话指的并非是 `frequency_penalty` 固定为 0.1 而是指在检测到退化时下一次请求 +0.1，目前各个翻译器都会自动处理，所以不用关注这个参数

谢谢回复
