### ISSUE TITLE
翻译卡住无法继续，罚站

### ISSUE THREAD

**Issue by tangmu1008** [neavo/OneClickLLAMA#8]
翻译到这就卡着不动了，暂停重新继续翻译会动一下下然后继续罚站不继续翻译

![Snipaste_2024-11-11_17-25-25](https://github.com/user-attachments/assets/274280b8-96e0-4a21-a899-bf5079a9506b)
![Snipaste_2024-11-11_17-25-38](https://github.com/user-attachments/assets/ffb32928-4801-4428-9edb-d2847f7b98fb)
还有一种问题译文文本未通过检查，稍后将重试 - 译文与原文完全相同                                                                 |
+---------------------------------------------------------------------------------------------------------------------+
| 格式原文示例已添加：                                                                                                |
| {"0": "Love is the flame in the depth of the soul, warm and never extinguished."}                                   |
+---------------------------------------------------------------------------------------------------------------------+
| 格式译文示例已添加：                                                                                                |
| {"0": "爱情是灵魂深处的火焰，温暖且永不熄灭。"}                                                                     |
+---------------------------------------------------------------------------------------------------------------------+
| Pwcog --> Pwcog                                                                                                     |
| _goods --> _goods                                                                                                   |
| reloadMapIfUpdated --> reloadMapIfUpdated                  

下面是日志：
[新建 文本文档 (3).txt](https://github.com/user-attachments/files/17700139/3.txt)

**Comment by neavo** [comment]
试一下最新的测试版看看，可以把设置里的超时时间调短一点

另外，这种代码文本先自己清洗一下，AI 处理不好的
